//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UrunKabul
    {
        public int ID { get; set; }
        public Nullable<int> CariID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<System.DateTime> GelisTarih { get; set; }
        public Nullable<System.DateTime> CikisTarih { get; set; }
        public string UrunSeriNo { get; set; }
        public Nullable<bool> Durum { get; set; }
        public string UrunDurumDetay { get; set; }
    
        public virtual Tbl_Cari Tbl_Cari { get; set; }
        public virtual Tbl_Personel Tbl_Personel { get; set; }
    }
}
